### ISSUE TITLE
跪求大佬回复

### ISSUE THREAD

**Issue by abs612** [zmh-program/go-proxy-bingai#1]
大佬，我用 new-api 这个项目，对接了您的版本（`https://github.com/CaoYunzhou/cocopilot-gpt/pull/7`）。但是有时候回复出现乱码，该怎么解决？
![image](https://github.com/zmh-program/go-proxy-bingai/assets/144533817/07c71872-12c8-44ff-b26f-6f889560ae68)

new-api 项目地址：https://github.com/Calcium-Ion/new-api

**Comment by zmh-program** [comment]
有可能是 unicode 字符断裂，比如 \\u0000 断裂为 "\\u00" "0" "0" 将识别为三个无法识别的字符。我并不是两个项目的原作者，同时，我建议你去 new api 问此问题而非我，仅仅是，一个 fork。感谢。

**Comment by zmh-program** [comment]
而且，你似乎，把issue提错地方了，这里是  zmh-program/go-proxy-bingai，是bing逆向而不是copilot。

**Comment by abs612** [comment]
> 有可能是 unicode 字符断裂，比如 \u0000 断裂为 "\u00" "0" "0" 将识别为三个无法识别的字符。我并不是两个项目的原作者，同时，我建议你去 new api 问此问题而非我，仅仅是，一个 fork。感谢。

谢谢大佬解答

**Comment by abs612** [comment]
> 而且，你似乎，把issue提错地方了，这里是 zmh-program/go-proxy-bingai，是bing逆向而不是copilot。

我原本就想在大佬那个项目提问的，但是没有提问的地方
![image](https://github.com/zmh-program/go-proxy-bingai/assets/144533817/cfbe4b54-5a47-4c0e-ba9d-28a34d685b51)

**Comment by zmh-program** [comment]
有可能是 fork 的问题

**Comment by abs612** [comment]
> 有可能是 fork 的问题

大佬回复真快。我打算换one-api试下，看能解决这个问题嘛。再次感谢大佬解答，没有大佬的无私奉献，我还用不上gpt-4。

不打扰大佬啦
